#!/usr/bin/env bash
#
# gen-tests.sh — emit N trivial JUnit 5 test classes (Gen000Test .. Gen<NNN>Test),
# one @Test each. The class set is what the fork axis multiplies: N classes with
# reuseForks=false means N cold forked JVMs.
#
# Usage:
#   tools/gen-tests.sh --fixed <N>   -> src/test/java/bench/fixed/n<N>/   (commit these)
#   tools/gen-tests.sh --gen   <N>   -> src/test/java/bench/gen/          (gitignored)
#
# --fixed is the ONE-TIME step that produces the committed tiers (n1, n10); run it
# by hand, then `git add` the result. --gen is what run-bench.sh calls for every
# N >= 50: the target directory is wiped first, so it always holds exactly N classes.
#
# Trivial bodies keep the signal about JVM startup, not test work. If the C2 on/off
# delta turns out flat, add a small compute loop in the @Test body so C2 has
# something worth compiling (see README, "If the C2 signal is flat").
set -euo pipefail

mode="${1:-}"
N="${2:-}"

case "$mode" in
  --fixed) pkg="bench.fixed.n${N}"; rel="src/test/java/bench/fixed/n${N}" ;;
  --gen)   pkg="bench.gen";         rel="src/test/java/bench/gen" ;;
  *) echo "usage: $0 --fixed <N> | --gen <N>" >&2; exit 2 ;;
esac

if ! [[ "$N" =~ ^[0-9]+$ ]]; then
  echo "error: N must be a non-negative integer, got '${N}'" >&2
  exit 2
fi

# Resolve repo root from this script's location so it works from any CWD.
root="$(cd "$(dirname "$0")/.." && pwd)"
dir="$root/$rel"

# Fresh slate: N is authoritative, never merged with a prior larger run.
rm -rf "$dir"
mkdir -p "$dir"

i=0
while [ "$i" -lt "$N" ]; do
  name="$(printf 'Gen%03dTest' "$i")"
  cat > "$dir/${name}.java" <<EOF
package ${pkg};

import org.junit.jupiter.api.Test;

/** Auto-generated by tools/gen-tests.sh — do not edit by hand. */
class ${name} {
    @Test
    void t() {
        // Intentionally trivial: this benchmark measures JVM startup/fork cost,
        // not the work inside a test.
    }
}
EOF
  i=$((i + 1))
done

echo "generated ${N} class(es) in ${rel} (package ${pkg})"
